import assert from "node:assert/strict";
import { MongoMemoryReplSet } from "mongodb-memory-server";
import mongoose from "mongoose";
import { NextRequest } from "next/server";
import { spawn } from "node:child_process";
import { connectDB } from "../src/lib/db";
import { signSession, hashPassword, type SessionPayload } from "../src/lib/auth";
import { POST as recibirOC } from "../src/app/api/ordenes-compra/[id]/recibir/route";
import { POST as recibirPedido } from "../src/app/api/pedidos/[id]/recibir/route";
import { GET as reporte } from "../src/app/api/reportes/productos/route";
import { GET as buscar } from "../src/app/api/busqueda/route";
import { opcionesBusqueda } from "../src/lib/busqueda";
import Producto from "../src/models/Producto";
import OrdenCompra from "../src/models/OrdenCompra";
import Pedido from "../src/models/Pedido";
import Movimiento from "../src/models/MovimientoInventario";
import Inventario from "../src/models/InventarioSucursal";
import Venta from "../src/models/Venta";
import Sucursal from "../src/models/Sucursal";
import User from "../src/models/User";
import Proveedor from "../src/models/Proveedor";

async function main() {
  const db = await MongoMemoryReplSet.create({replSet: {count: 1}});
  process.env.MONGODB_URI = db.getUri("titos_pruebas");
  process.env.JWT_SECRET = "solo-pruebas-locales-sin-datos-reales-2026";
  let servidor: ReturnType<typeof spawn> | undefined;
  try {
    await connectDB();
    const a = await Sucursal.create({nombre: "Sucursal prueba A"});
    const b = await Sucursal.create({nombre: "Sucursal prueba B"});
    const user = await User.create({email: "pruebas@titos.local", nombre: "Pruebas locales", role: "matriz", passwordHash: await hashPassword("Pruebas-locales-2026")});
    await User.create({email: "sucursal@titos.local", nombre: "Sucursal prueba", role: "sucursal", sucursalId: a._id, passwordHash: await hashPassword("Pruebas-locales-2026")});
    const proveedor = await Proveedor.create({nombre: "Proveedor prueba"});
    const p = await Producto.create({nombre: "Café prueba", sku: "CAFE.01", categoria: "Abarrotes", unidad: "pieza", existenciaMatriz: 10, precioCompra: 5, precioVenta: 10});
    const kg = await Producto.create({nombre: "Carne prueba", sku: "KG01", categoria: "Carnes", unidad: "kg", existenciaMatriz: 10, precioCompra: 5, precioVenta: 20});
    const base: SessionPayload = {userId: String(user._id), email: user.email, nombre: user.nombre, role: "matriz", sucursalId: null};
    const admin = await signSession(base);
    const branch = await signSession({...base, role: "sucursal", sucursalId: String(a._id)});
    const denied = await signSession({...base, permisos: ["pos.vender"]});
    function req(url: string, token = admin, items?: unknown) { return new NextRequest(`http://localhost${url}`, {method: items === undefined ? "GET" : "POST", headers: {cookie: `titos_session=${token}`, "Content-Type": "application/json"}, ...(items === undefined ? {} : {body: JSON.stringify({items})})}); }
    const context = (id: unknown) => ({params: Promise.resolve({id: String(id)})});
    const orden = () => OrdenCompra.create({folio: `OC-${new mongoose.Types.ObjectId()}`, proveedorId: proveedor._id, estado: "solicitada", items: [{productoId: p._id, nombreProducto: p.nombre, cantidadOrdenada: 10}, {productoId: kg._id, nombreProducto: kg.nombre, cantidadOrdenada: 5}]});
    const oc = await orden();
    const entradas = [{productoId: String(p._id), cantidadRecibida: 7, notaRecepcion: "Faltan tres"}, {productoId: String(kg._id), cantidadRecibida: 4.5, notaRecepcion: "Diferencia de peso"}];
    assert.equal((await recibirOC(req("/api/oc", denied, entradas), context(oc._id))).status, 403);
    assert.equal((await recibirOC(req("/api/oc", admin, [entradas[0], {...entradas[1], cantidadRecibida: -1}]), context(oc._id))).status, 400);
    assert.equal((await Producto.findById(p._id)).existenciaMatriz, 10);
    const respuestas = await Promise.all([recibirOC(req("/api/oc", admin, entradas), context(oc._id)), recibirOC(req("/api/oc", admin, entradas), context(oc._id))]);
    assert.deepEqual(respuestas.map((r) => r.status).sort(), [200, 409]);
    assert.equal((await Producto.findById(p._id)).existenciaMatriz, 17);
    const guardada = await OrdenCompra.findById(oc._id);
    assert.equal(guardada.items[0].cantidadOrdenada, 10);
    assert.equal(guardada.items[0].notaRecepcion, "Faltan tres");
    assert.equal(await Movimiento.countDocuments({ordenCompraId: oc._id}), 2);
    const fallo = await orden();
    fallo.items[1].productoId = new mongoose.Types.ObjectId(); await fallo.save();
    assert.equal((await recibirOC(req("/api/oc", admin, [entradas[0], {...entradas[1], productoId: String(fallo.items[1].productoId)}]), context(fallo._id))).status, 400);
    assert.equal((await Producto.findById(p._id)).existenciaMatriz, 17, "Rollback del primer producto si falla el segundo");
    assert.equal(await Movimiento.countDocuments({ordenCompraId: fallo._id}), 0);
    const pedido = await Pedido.create({folio: "PED-TEST", sucursalId: a._id, corte: "2026-09-08", estado: "surtido", items: [{productoId: p._id, nombreProducto: p.nombre, unidad: "pieza", cantidadPedida: 10, cantidadSurtida: 10}, {productoId: kg._id, nombreProducto: kg.nombre, unidad: "kg", requierePesaje: true, cantidadPedida: 5, cantidadSurtida: 5}]});
    assert.equal((await recibirPedido(req("/api/pedido", branch, entradas), context(pedido._id))).status, 400);
    assert.equal(await Inventario.countDocuments(), 0, "Falta peso: ninguna existencia parcial");
    const otraSucursal = await signSession({...base, role: "sucursal", sucursalId: String(b._id)});
    assert.equal((await recibirPedido(req("/api/pedido", otraSucursal, entradas), context(pedido._id))).status, 403);
    const recibidos = entradas.map((e) => ({...e, pesoRecibidoKg: 4.5}));
    assert.equal((await recibirPedido(req("/api/pedido", branch, recibidos), context(pedido._id))).status, 200);
    assert.equal((await recibirPedido(req("/api/pedido", branch, recibidos), context(pedido._id))).status, 409);
    assert.equal((await Inventario.findOne({productoId: p._id, sucursalId: a._id})).stockActual, 7);
    assert.equal((await Pedido.findById(pedido._id)).items[0].notaRecepcion, "Faltan tres");
    console.log("OK: permisos, cantidades inválidas, notas, rollback y reintentos sin duplicación");
    function venta(folio: string, producto = p, sucursal = a, cantidad = 1, extra = {}) { return {folio, sucursalId: sucursal._id, usuarioId: user._id, cajaSesionId: new mongoose.Types.ObjectId(), corte: "2026-09-08", fecha: new Date("2026-09-08T20:00:00Z"), items: [{productoId: producto._id, nombreProducto: producto.nombre, sku: producto.sku, unidad: producto.unidad, cantidad, precioUnitario: 10, subtotal: cantidad * 10}], total: cantidad * 10, ...extra}; }
    await Venta.insertMany([...Array.from({length: 2101}, (_, i) => venta(`V-${i}`)), venta("V-B", p, b, 3), venta("V-KG", kg, a, 2.5), venta("V-CANCELADA", p, a, 99, {estado: "cancelada"}), venta("V-NOTA", p, a, 100, {esVentas2: true}), venta("V-FUERA", p, a, 99, {corte: "2026-09-07"})]);
    const url = "/api/reportes/productos?desde=2026-09-08&hasta=2026-09-08";
    assert.equal((await reporte(req(url, ""))).status, 401);
    assert.equal((await reporte(req(url, denied))).status, 403);
    const datos = await (await reporte(req(url))).json();
    assert.equal(datos.totales.piezas, 2104); assert.equal(datos.totales.importe, 21040); assert.equal(datos.total, 1);
    assert.equal(datos.filas[0].sucursales.find((s: {id: string}) => s.id === String(b._id)).cantidad, 3);
    assert.equal((await (await reporte(req(url + "&unidad=kg"))).json()).totales.kg, 2.5);
    assert.equal((await (await reporte(req(url + "&notas=incluir"))).json()).totales.piezas, 2204);
    assert.equal((await (await reporte(req(url + "&notas=solo"))).json()).totales.piezas, 100);
    assert.equal((await (await reporte(req(url + "&q=CAFE.01"))).json()).total, 1);
    assert.equal((await (await reporte(req(url + "&q=.*"))).json()).total, 0, "Regex literal");
    assert.equal((await reporte(req(url + "&unidad=todas"))).status, 400);
    assert.equal((await reporte(req("/api/reportes/productos?desde=2026-02-30&hasta=2026-09-08"))).status, 400);
    const asc = await (await reporte(req(url + "&unidad=todas&medida=importe&orden=asc"))).json();
    assert.equal(asc.filas[0]._id.sku, "KG01");
    assert.equal((await (await buscar(req("/api/busqueda?q=cafe"))).json()).productos[0].label, "Café prueba");
    assert.equal((await (await buscar(req("/api/busqueda?q=cafe", denied))).json()).productos.length, 0);
    assert.equal(opcionesBusqueda("tipo de cambio", "matriz", () => true)[0].href, "/matriz/configuracion#tipo-cambio");
    assert.equal(opcionesBusqueda("tipo de cambio", "matriz", () => false).length, 0);
    await Venta.insertMany(Array.from({length: 55}, (_, i) => venta(`PAG-${i}`, {...p.toObject(), _id: new mongoose.Types.ObjectId(), sku: `PAG-${String(i).padStart(2, "0")}`, nombre: `Producto ${i}`}, a, i + 1, {corte: "2026-09-06"})));
    const pagUrl = "/api/reportes/productos?desde=2026-09-06&hasta=2026-09-06";
    const pag1 = await (await reporte(req(pagUrl))).json();
    const pag2 = await (await reporte(req(pagUrl + "&pagina=2"))).json();
    assert.equal(pag1.total, 55); assert.equal(pag1.filas.length, 50); assert.equal(pag2.filas.length, 5);
    assert.equal(pag1.totales.piezas, 1540); assert.equal(pag2.totales.piezas, 1540);
    assert.equal(new Set([...pag1.filas, ...pag2.filas].map((r) => r._id.sku)).size, 55);
    console.log("OK: paginación de 55 productos con totales completos y sin duplicados");
    console.log("OK: reporte con 2,101+ ventas, sucursales, kg, notas, cancelaciones, fechas, búsqueda y permisos");
    if (process.argv.includes("--serve")) {
      await orden();
      await Pedido.create({folio: "PED-VISUAL", sucursalId: a._id, corte: "2026-09-08", estado: "surtido", items: [{productoId: p._id, nombreProducto: p.nombre, unidad: "pieza", cantidadPedida: 10, cantidadSurtida: 10}]});
      servidor = spawn("npm", ["run", "dev", "--", "--port", "3100"], {stdio: "inherit", env: {...process.env}});
      await new Promise<void>((resolve) => {servidor!.on("exit", () => resolve()); process.on("SIGTERM", () => {servidor?.kill(); resolve();}); process.on("SIGINT", () => {servidor?.kill(); resolve();});});
    }
  } finally { servidor?.kill(); await mongoose.disconnect(); await db.stop(); }
}
main().catch((error) => {console.error(error); process.exitCode = 1;});
