import assert from "node:assert/strict";
import mongoose from "mongoose";
import { MongoMemoryReplSet } from "mongodb-memory-server";
import { NextRequest } from "next/server";
import { spawn } from "node:child_process";
import { connectDB } from "../src/lib/db";
import { signSession, hashPassword } from "../src/lib/auth";
import { asegurarRolesSemilla } from "../src/lib/roles";
import { sesionVigente } from "../src/lib/sesionVigente";
import { accesoApiPuesto, accesoPaginaPuesto } from "../src/lib/accesoPuestos";
import { tienePermiso } from "../src/lib/permisos";
import { requiereNipCaja } from "../src/lib/nipCaja";
import { buscarSupervisorPorNip } from "../src/lib/supervisores";
import { GET as listar, POST as alta } from "../src/app/api/usuarios/route";
import { PATCH as editar } from "../src/app/api/usuarios/[id]/route";
import { POST as nuevoDepartamento } from "../src/app/api/departamentos/route";
import { PATCH as editarDepartamento } from "../src/app/api/departamentos/[id]/route";
import { POST as nuevoRol } from "../src/app/api/roles/route";
import { PATCH as editarRol } from "../src/app/api/roles/[id]/route";
import { GET as productos, POST as crearProducto } from "../src/app/api/productos/route";
import { proxy } from "../src/proxy";
import User from "../src/models/User";
import Rol from "../src/models/Rol";
import Sucursal from "../src/models/Sucursal";
import Configuracion from "../src/models/Configuracion";

async function main() {
  const mongo = await MongoMemoryReplSet.create({ replSet: { count: 1 } });
  process.env.MONGODB_URI = mongo.getUri("usuarios_sept15_pruebas");
  process.env.JWT_SECRET = "pruebas-usuarios-sept15-aisladas";
  let server: ReturnType<typeof spawn> | undefined;
  try {
    await connectDB(); await asegurarRolesSemilla();
    const admin = await User.create({ nombre: "Administración · prueba", email: "admin@prueba.local", role: "matriz", passwordHash: await hashPassword("Prueba-local-2026") });
    const claims = { userId: String(admin._id), nombre: admin.nombre, email: admin.email, role: "matriz" as const, sucursalId: null };
    const token = await signSession(claims);
    const req = (path: string, method = "GET", body?: unknown, auth = token) => new NextRequest(`http://localhost:3100${path}`, { method, headers: { cookie: `titos_session=${auth}`, "content-type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    const ctx = (id: unknown) => ({ params: Promise.resolve({ id: String(id) }) });
    const suc = await Sucursal.create({ nombre: "Tienda de prueba", direccion: "Prueba" });
    const dep = await nuevoDepartamento(req("/api/departamentos", "POST", { nombre: "Operación", descripcion: "Datos de prueba" }));
    assert.equal(dep.status, 201, await dep.clone().text());
    const departamentoId = (await dep.json())._id;
    assert.equal((await nuevoDepartamento(req("/api/departamentos", "POST", { nombre: " OPERACION " }))).status, 409);
    assert.equal((await nuevoDepartamento(req("/api/departamentos", "POST", { nombre: "Sin sesión" }, ""))).status, 401);
    const rolResponse = await nuevoRol(req("/api/roles", "POST", { nombre: "Consulta de catálogo", ambito: "matriz", departamentoId, permisos: ["productos.administrar"] }));
    assert.equal(rolResponse.status, 201);
    const rolId = (await rolResponse.json())._id;
    assert.equal((await Rol.findById(rolId)).departamentoId.toString(), departamentoId);
    assert.equal((await editarDepartamento(req("/api/departamentos/x", "PATCH", { activo: false }), ctx(departamentoId))).status, 409);
    assert.equal((await editarRol(req(`/api/roles/${rolId}`, "PATCH", { departamentoId: "invalido" }), ctx(rolId))).status, 400);
    const datos = { nombre: "Usuario de prueba", email: "usuario@prueba.local", role: "matriz", rolId, password: "Prueba-local-2026", permisosIndividuales: ["productos.administrar"], permisosSoloConsulta: ["productos.administrar"] };
    const creado = await alta(req("/api/usuarios", "POST", datos));
    assert.equal(creado.status, 201, await creado.clone().text());
    const id = (await creado.json())._id;
    const usuarioClaims = { ...claims, userId: id, email: datos.email, nombre: datos.nombre };
    const usuarioToken = await signSession(usuarioClaims);
    let session = (await sesionVigente(usuarioClaims))!;
    assert.equal(accesoApiPuesto(session, "/api/productos", "GET"), true);
    for (const method of ["POST", "PATCH", "DELETE"]) assert.equal(accesoApiPuesto(session, "/api/productos", method), false);
    assert.equal((await productos(req("/api/productos", "GET", undefined, usuarioToken))).status, 200);
    assert.equal((await crearProducto(req("/api/productos", "POST", {}, usuarioToken))).status, 401);
    assert.equal((await proxy(req("/api/productos", "POST", {}, usuarioToken))).status, 403);
    assert.equal(accesoPaginaPuesto(session, "/matriz/productos"), true);
    assert.equal(accesoPaginaPuesto(session, "/matriz/usuarios"), false);
    assert.equal((await editar(req(`/api/usuarios/${id}`, "PATCH", { permisosIndividuales: ["reportes.ver"], permisosSoloConsulta: [] }), ctx(id))).status, 200);
    session = (await sesionVigente(usuarioClaims))!;
    assert.equal(tienePermiso(session, "reportes.ver"), true);
    assert.equal(tienePermiso(session, "reportes.productos"), false, "Quitar un reporte no se revierte por el permiso agrupado del puesto");
    assert.equal(accesoApiPuesto(session, "/api/productos", "GET"), false, "Revocación con la misma sesión");
    assert.equal((await editar(req(`/api/usuarios/${id}`, "PATCH", { permisosIndividuales: [] }), ctx(id))).status, 200);
    assert.deepEqual((await sesionVigente(usuarioClaims))!.permisos, []);
    assert.equal((await editar(req(`/api/usuarios/${id}`, "PATCH", { permisosIndividuales: null }), ctx(id))).status, 200);
    assert.equal(accesoApiPuesto((await sesionVigente(usuarioClaims))!, "/api/productos", "POST"), true);
    assert.equal((await editar(req(`/api/usuarios/${admin._id}`, "PATCH", { permisosIndividuales: [] }), ctx(admin._id))).status, 400);
    assert.equal((await editar(req(`/api/usuarios/${id}`, "PATCH", { permisosIndividuales: ["inexistente"] }), ctx(id))).status, 400);
    assert.equal((await editar(req(`/api/usuarios/${id}`, "PATCH", { permisosIndividuales: ["pedidos.crear"] }), ctx(id))).status, 400, "No cruza los límites de matriz y sucursal");
    await User.updateOne({ _id: id }, { $set: { rolId: null, permisosIndividuales: [], permisosSoloConsulta: [] } });
    assert.deepEqual((await sesionVigente({ ...usuarioClaims, permisos: ["usuarios.administrar"] }))!.permisos, [], "Un JWT viejo no recupera accesos");
    const cajero = await Rol.findOne({ codigoSistema: "pos-cajero" });
    const gerente = await Rol.findOne({ codigoSistema: "gerente-tienda" });
    assert.equal(requiereNipCaja(cajero), false); assert.equal(requiereNipCaja(gerente), true);
    assert.equal(requiereNipCaja({ nombre: "Supervisor", esSupervisor: true }), false);
    const cajeroResponse = await alta(req("/api/usuarios", "POST", { nombre: "Cajero de prueba", email: "caja@prueba.local", role: "sucursal", rolId: String(cajero._id), sucursalId: String(suc._id), password: "Prueba-local-2026" }));
    assert.equal(cajeroResponse.status, 201, await cajeroResponse.clone().text());
    const cajeroId = (await cajeroResponse.json())._id;
    assert.equal((await editar(req(`/api/usuarios/${cajeroId}`, "PATCH", { nipOperacion: "112233" }), ctx(cajeroId))).status, 400);
    await Configuracion.create({ clave: "general", nipCreacionSupervisorHash: await hashPassword("998877") });
    const gerenteDatos = { nombre: "Gerente de prueba", email: "gerente@prueba.local", role: "sucursal", rolId: String(gerente._id), sucursalId: String(suc._id), password: "Prueba-local-2026", nipCreacionSupervisor: "998877" };
    assert.equal((await alta(req("/api/usuarios", "POST", gerenteDatos))).status, 400);
    const gerenteResponse = await alta(req("/api/usuarios", "POST", { ...gerenteDatos, nipOperacion: "112233" }));
    assert.equal(gerenteResponse.status, 201, await gerenteResponse.clone().text());
    const gerenteId = (await gerenteResponse.json())._id;
    assert.equal((await buscarSupervisorPorNip("112233", suc._id))?.id, gerenteId);
    assert.equal((await editar(req(`/api/usuarios/${gerenteId}`, "PATCH", { nipOperacion: "223344" }), ctx(gerenteId))).status, 200);
    assert.equal(await buscarSupervisorPorNip("112233", suc._id), null);
    assert.equal((await buscarSupervisorPorNip("223344", suc._id))?.id, gerenteId);
    assert.equal((await editar(req(`/api/usuarios/${gerenteId}`, "PATCH", { rolId: String(cajero._id) }), ctx(gerenteId))).status, 200);
    assert.equal(await buscarSupervisorPorNip("223344", suc._id), null);
    assert.equal((await User.findById(gerenteId)).nipOperacionHash, "");
    const listado = await (await listar(req("/api/usuarios"))).json();
    assert.equal(listado.departamentos[0].nombre, "Operación");
    assert.equal(JSON.stringify(listado).includes("nipOperacionHash"), false);
    assert.equal(JSON.stringify(listado).includes("passwordHash"), false);
    assert.equal((await editarRol(req(`/api/roles/${rolId}`, "PATCH", { departamentoId: null }), ctx(rolId))).status, 200);
    assert.equal((await editarDepartamento(req(`/api/departamentos/${departamentoId}`, "PATCH", { activo: false }), ctx(departamentoId))).status, 200);
    assert.equal((await editarRol(req(`/api/roles/${rolId}`, "PATCH", { departamentoId }), ctx(rolId))).status, 400);
    // Deja datos identificados para la revisión visual del formulario local.
    await editarDepartamento(req(`/api/departamentos/${departamentoId}`, "PATCH", { activo: true }), ctx(departamentoId));
    await editarRol(req(`/api/roles/${rolId}`, "PATCH", { departamentoId }), ctx(rolId));
    console.log("OK: departamentos, duplicados, asignación, NIP exclusivo de gerente, edición y revocación, permisos individuales, solo consulta, API, navegación, herencia, misma sesión y privacidad.");
    if (process.argv.includes("--serve")) {
      server = spawn("npm", ["run", "dev", "--", "--port", "3100"], { stdio: "inherit", env: process.env });
      await new Promise<void>((resolve) => { server!.on("exit", resolve); process.on("SIGTERM", () => { server?.kill(); resolve(); }); });
    }
  } finally { server?.kill(); await mongoose.disconnect(); await mongo.stop(); }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
