import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import mongoose from "mongoose";
import { MongoMemoryReplSet } from "mongodb-memory-server";
import { NextRequest } from "next/server";
import { connectDB } from "../src/lib/db";
import { hashPassword, signSession } from "../src/lib/auth";
import { asegurarRolesSemilla } from "../src/lib/roles";
import { sesionVigente } from "../src/lib/sesionVigente";
import { accesoApiPuesto, accesoPaginaPuesto } from "../src/lib/accesoPuestos";
import { calcularPromociones } from "../src/lib/motorPromociones";
import { validarPromocion } from "../src/lib/promociones";
import { resumenArqueos, type FilaArqueo } from "../src/lib/reporteArqueos";
import { fechaEnZona } from "../src/lib/zonasHorarias";
import User from "../src/models/User";
import Rol from "../src/models/Rol";
import Producto from "../src/models/Producto";
import Sucursal from "../src/models/Sucursal";
import Caja from "../src/models/CajaSesion";
import Arqueo from "../src/models/Arqueo";
import Promocion from "../src/models/Promocion";
import Inventario from "../src/models/InventarioSucursal";
import Venta from "../src/models/Venta";
import { POST as vender } from "../src/app/api/ventas/route";
import { POST as altaPromo } from "../src/app/api/promociones/route";
import { GET as arqueos } from "../src/app/api/reportes/arqueos/route";
import { GET as productosReporte } from "../src/app/api/reportes/productos/route";
import { GET as sucursalesLista, POST as crearSucursal } from "../src/app/api/sucursales/route";
import { buscarSupervisorPorNip } from "../src/lib/supervisores";
import { POST as altaProducto } from "../src/app/api/productos/route";
import { PATCH as editarProducto } from "../src/app/api/productos/[id]/route";
import { FISCAL_INICIAL } from "../src/lib/fiscalProducto";
import { POST as abrirCaja } from "../src/app/api/caja/abrir/route";
import { PATCH as configurar } from "../src/app/api/configuracion/route";
import { GET as corteDiario } from "../src/app/api/cortes/diario/route";
import { escaparCorte, detalleTarjetasDiario } from "../src/lib/corteDiario";
import { costoRecepcion } from "../src/lib/costosRecepcion";
import { REGLAS_OPERACION } from "../src/lib/reglasOperacion";
import OrdenCompra from "../src/models/OrdenCompra";
import Proveedor from "../src/models/Proveedor";
import { POST as recibirCompra } from "../src/app/api/ordenes-compra/[id]/recibir/route";
import { POST as corregirDia } from "../src/app/api/ventas/corregir-dia/route";

async function main() {
  const mongo = await MongoMemoryReplSet.create({ replSet: { count: 1 } });
  process.env.MONGODB_URI = mongo.getUri("titos_jessica_pruebas");
  process.env.JWT_SECRET = "solo-pruebas-jessica-2026";
  let server: ReturnType<typeof spawn> | undefined;
  try {
    const fiscalCosto = {...FISCAL_INICIAL, iva:"8" as const, iepsTipo:"porcentaje" as const, iepsValor:10};
    const reglasCosto = {...REGLAS_OPERACION,costosCompra:"sin_impuestos" as const,baseIvaCompra:"costo_ieps" as const};
    assert.deepEqual(costoRecepcion(2,100,fiscalCosto,reglasCosto), {subtotal:200,ieps:20,iva:17.6,total:237.6});
    assert.deepEqual(costoRecepcion(2,118.8,fiscalCosto,{...reglasCosto,costosCompra:"incluidos"}), {subtotal:200,ieps:20,iva:17.6,total:237.6});
    assert.equal(costoRecepcion(2,100,fiscalCosto,{...reglasCosto,baseIvaCompra:"costo"}).total,236);
    assert.throws(()=>costoRecepcion(1,100,fiscalCosto,REGLAS_OPERACION));
    await connectDB();
    await Rol.create({ nombre: "Cajero", ambito: "sucursal", permisos: ["pos.vender"] });
    await Rol.create({ nombre: "Supervisor", ambito: "sucursal", permisos: ["pos.vender"] });
    await asegurarRolesSemilla(); await asegurarRolesSemilla();
    assert.equal(await Rol.countDocuments({ retirado: { $ne: true } }), 7);
    const gerenteRol = await Rol.findOne({ codigoSistema: "gerente-tienda" });
    gerenteRol.nombre = "Gerente de tienda"; await gerenteRol.save();
    await asegurarRolesSemilla();
    assert.equal(await Rol.countDocuments({ codigoSistema: "gerente-tienda" }), 1);
    const a = await Sucursal.create({ nombre: "Sucursal A prueba", clave: "A-PR" });
    const b = await Sucursal.create({ nombre: "Sucursal B prueba", clave: "B-PR" });
    const admin = await User.create({ nombre: "Admin de prueba", email: "pruebas@titos.local", role: "matriz", passwordHash: await hashPassword("Pruebas-locales-2026") });
    const gerente = await User.create({ nombre: "Gerente de prueba", email: "gerente@titos.local", role: "sucursal", sucursalId: a._id, rolId: gerenteRol._id, passwordHash: await hashPassword("Pruebas-locales-2026"), nipOperacionHash: await hashPassword("918273") });
    const payload = (u: typeof admin) => ({ userId: String(u._id), nombre: u.nombre, email: u.email, role: u.role, sucursalId: u.sucursalId ? String(u.sucursalId) : null });
    const token = await signSession(payload(admin));
    const gerenteToken = await signSession(payload(gerente));
    const req = (url: string, method = "GET", body?: unknown, auth = token) => new NextRequest(`http://localhost${url}`, { method, headers: { cookie: `titos_session=${auth}`, "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
    const sesion = (await sesionVigente(payload(gerente)))!;
    assert.equal(accesoPaginaPuesto(sesion, "/sucursal/reportes"), true);
    assert.equal(accesoApiPuesto(sesion, "/api/reportes/arqueos", "GET"), true);
    assert.equal(accesoApiPuesto(sesion, "/api/productos", "POST"), false);
    assert.equal((await crearSucursal(req("/api/sucursales", "POST", { nombre: "Prohibida" }, gerenteToken))).status, 401);
    assert.equal((await sucursalesLista(req("/api/sucursales", "GET", undefined, gerenteToken))).status, 200);
    assert.equal((await productosReporte(req("/api/reportes/productos?desde=2026-09-01&hasta=2026-09-30", "GET", undefined, gerenteToken))).status, 200);
    assert.equal(await buscarSupervisorPorNip("918273", b._id), null);
    assert.ok(await buscarSupervisorPorNip("918273", a._id));
    const caja = await Caja.create({ sucursalId: a._id, usuarioAperturaId: gerente._id, efectivoInicial: 1000 });
    const now = new Date();
    const day = fechaEnZona(now);
    const auditoria = { sucursalId: a._id, cajaSesionId: caja._id, usuarioId: gerente._id, supervisorId: gerente._id, supervisorNombre: "Gerente de prueba", tokenHash: "no-token", estado: "guardado", consultadoEn: now, venceEn: now, resumen: {}, efectivoInicial: 1000, efectivoInicialUsd: 0, efectivoEsperado: 1000, efectivoContado: 980, diferencia: -20, efectivoEsperadoUsd: 0, efectivoContadoUsd: 3, diferenciaUsd: 3, guardadoEn: now };
    await Arqueo.create({ ...auditoria, guardadoEn: new Date(now.getTime() - 1000), diferencia: -500 });
    await Arqueo.create(auditoria);
    const reporte = await (await arqueos(req(`/api/reportes/arqueos?desde=${day}&hasta=${day}`))).json();
    assert.equal(reporte.filas.length, 1, "No duplica arqueos de una misma caja");
    assert.equal(reporte.resumen.faltantes, -20); assert.equal(reporte.resumen.sobrantesUsd, 3);
    assert.equal(JSON.stringify(reporte).includes("no-token"), false);
    assert.equal((await arqueos(req(`/api/reportes/arqueos?desde=${day}&hasta=${day}`, "GET", undefined, gerenteToken))).status, 200);
    const summary = resumenArqueos([{ diferencia: -20, diferenciaUsd: 3 }, { diferencia: 10, diferenciaUsd: -2 }] as FilaArqueo[]);
    assert.equal(summary.faltantes, -20); assert.equal(summary.sobrantes, 10);
    const p1 = await Producto.create({ nombre: "Producto caro prueba", sku: "J-100", categoria: "Pruebas", area: "Abarrotes", unidad: "pieza", precioVenta: 100, existenciaMatriz: 100 });
    const p2 = await Producto.create({ nombre: "Producto barato prueba", sku: "J-060", categoria: "Pruebas", area: "Abarrotes", unidad: "pieza", precioVenta: 60, existenciaMatriz: 100 });
    const fiscal = { ...FISCAL_INICIAL, iva: "8", claveProdServ: "50101500" };
    const fiscalAlta = await altaProducto(req("/api/productos", "POST", { nombre: "Fiscal prueba", sku: "J-FISCAL", categoria: "Pruebas", unidad: "pieza", fiscal }));
    assert.equal(fiscalAlta.status, 201);
    const productoFiscal = await fiscalAlta.json();
    assert.equal(productoFiscal.fiscal.iva, "8");
    const fiscalEdit = await editarProducto(req(`/api/productos/${productoFiscal._id}`, "PATCH", { fiscal: { ...fiscal, iva: "16" } }), { params: Promise.resolve({ id: productoFiscal._id }) });
    assert.equal(fiscalEdit.status, 200);
    assert.equal((await fiscalEdit.json()).fiscal.iva, "16");
    assert.equal((await editarProducto(req(`/api/productos/${productoFiscal._id}`, "PATCH", { fiscal: { ...fiscal, claveProdServ: "ABC" } }), { params: Promise.resolve({ id: productoFiscal._id }) })).status, 400);
    await Inventario.create([{ sucursalId: a._id, productoId: p1._id, stockActual: 100 }, { sucursalId: a._id, productoId: p2._id, stockActual: 100 }]);
    const base = { nombre: "Segundo a mitad prueba", tipo: "combinacion", valor: 0, alcance: "productos", productos: [String(p1._id), String(p2._id)], categorias: [], areas: [], sucursales: [String(a._id)], unidad: "pieza", inicio: day, fin: day, estado: "activa", lleva: 2, bonifica: 1, porcentajeBeneficio: 50, combinada: true, prioridad: 1 };
    const regla = { ...validarPromocion(base), _id: "1" };
    const items = [{ productoId: String(p1._id), cantidad: 1, precio: 100, unidad: "pieza" }, { productoId: String(p2._id), cantidad: 1, precio: 60, unidad: "pieza" }];
    assert.equal(calcularPromociones(items, [regla], day).total, 130);
    assert.equal(calcularPromociones(items, [{ ...regla, porcentajeBeneficio: 100 }], day).total, 100);
    assert.equal(calcularPromociones(items, [{ ...regla, combinada: false }], day).total, 160);
    assert.equal(calcularPromociones(items, [{ ...regla, estado: "borrador" }], day).total, 160);
    assert.equal(calcularPromociones(items, [{ ...regla, inicio: "2099-01-01" }], day).total, 160);
    const kilos = [{ productoId: "kg", cantidad: 1.5, precio: 100, unidad: "kg" }];
    assert.equal(calcularPromociones(kilos, [{ ...regla, productos: ["kg"], unidad: "kg", lleva: 1.5, bonifica: 0.5, porcentajeBeneficio: 100 }], day).total, 100);
    assert.equal(calcularPromociones(items, [regla, { ...regla, _id: "2", tipo: "porcentaje", valor: 99, prioridad: 2 }], day).total, 130, "No acumula descuento en artículos de una combinación");
    assert.equal((await altaPromo(req("/api/promociones", "POST", base))).status, 201);
    assert.equal((await altaPromo(req("/api/promociones", "POST", base, gerenteToken))).status, 401);
    const ventaBody = { clienteOperacionId: "jessica-prueba-1", items: items.map((i) => ({ productoId: i.productoId, cantidad: i.cantidad })), pagos: [{ metodoPago: "efectivo", monto: 130 }], montoRecibido: 150 };
    const res = await vender(req("/api/ventas", "POST", ventaBody, gerenteToken));
    assert.equal(res.status, 201, await res.clone().text());
    const venta = await res.json();
    assert.equal(venta.total, 130); assert.equal(venta.descuento, 30); assert.equal(venta.cambio, 20);
    assert.equal(venta.items.find((i: { sku: string }) => i.sku === "J-060").precioUnitario, 30);
    assert.equal((await vender(req("/api/ventas", "POST", ventaBody, gerenteToken))).status, 200);
    assert.equal(await Venta.countDocuments({ clienteOperacionId: "jessica-prueba-1" }), 1);
    assert.equal((await vender(req("/api/ventas", "POST", { ...ventaBody, clienteOperacionId: "precio-manipulado", pagos: [{ metodoPago: "efectivo", monto: 1 }] }, gerenteToken))).status, 400);
    await Promocion.updateMany({}, { estado: "archivado" });
    assert.equal((await altaPromo(req("/api/promociones", "POST", { ...base, nombre: "Sin cobro de prueba", tipo: "porcentaje", valor: 100 }))).status, 201);
    const gratuita = await vender(req("/api/ventas", "POST", { clienteOperacionId: "gratis", items: ventaBody.items, pagos: [] }, gerenteToken));
    assert.equal(gratuita.status, 201, await gratuita.clone().text());
    assert.equal((await gratuita.json()).total, 0);
    await Promocion.updateMany({ nombre: "Sin cobro de prueba" }, { estado: "archivado" });
    await Promocion.updateMany({ nombre: base.nombre }, { estado: "activa" });
    const gerenteB = await User.create({ nombre: "Gerente B", email: "b@titos.local", role: "sucursal", sucursalId: b._id, rolId: gerenteRol._id, passwordHash: await hashPassword("Pruebas-locales-2026") });
    const tokenB = await signSession(payload(gerenteB));
    assert.equal((await configurar(req("/api/configuracion", "PATCH", { fondoCajaMxn: 1250 }, gerenteToken))).status, 401);
    assert.equal((await configurar(req("/api/configuracion", "PATCH", { fondoCajaMxn: -1 }))).status, 400);
    assert.equal((await configurar(req("/api/configuracion", "PATCH", { fondoCajaMxn: 1250 }))).status, 200);
    assert.equal((await abrirCaja(req("/api/caja/abrir", "POST", { efectivoInicial: 1000 }, tokenB))).status, 409);
    const aperturaBody = { efectivoInicial: 1250, clienteOperacionId: "fondo-prueba-B" };
    const apertura = await abrirCaja(req("/api/caja/abrir", "POST", aperturaBody, tokenB));
    assert.equal(apertura.status, 201);
    assert.equal((await apertura.json()).efectivoInicial, 1250);
    assert.equal((await abrirCaja(req("/api/caja/abrir", "POST", aperturaBody, tokenB))).status, 200);
    assert.equal((await abrirCaja(req("/api/caja/abrir", "POST", aperturaBody, gerenteToken))).status, 403);
    assert.equal((await Caja.findById(caja._id)).efectivoInicial, 1000, "Una caja abierta conserva su fondo");
    await configurar(req("/api/configuracion", "PATCH", { fondoCajaMxn: 1000 }));
    await Venta.create({ folio: "NOTA-PRUEBA-50", sucursalId: a._id, cajaSesionId: caja._id, usuarioId: gerente._id, corte: day, total: 50, esVentas2: true, pagos: [{ metodoPago: "efectivo", monto: 50 }] });
    const con = await corteDiario(req(`/api/cortes/diario?dia=${day}&notas=con`));
    assert.equal(con.status, 200);
    const htmlCon = await con.text();
    assert.ok(htmlCon.includes("$180.00")); assert.ok(htmlCon.includes("NOTA-PRUEBA-50")); assert.ok(htmlCon.includes("Desglose fiscal pendiente"));
    const sin = await (await corteDiario(req(`/api/cortes/diario?dia=${day}&notas=sin`))).text();
    assert.ok(sin.includes("$130.00")); assert.ok(!sin.includes("NOTA-PRUEBA-50"));
    assert.equal((await corteDiario(req(`/api/cortes/diario?dia=${day}`, "GET", undefined, gerenteToken))).status, 200);
    assert.equal((await corteDiario(req("/api/cortes/diario?dia=2026-02-30"))).status, 400);
    assert.equal((await corteDiario(req(`/api/cortes/diario?dia=${day}&sucursalId=invalido`))).status, 400);
    assert.equal(escaparCorte('<script>"&'), "&lt;script&gt;&quot;&amp;");
    assert.ok(htmlCon.includes("Turnos pendientes de cerrar"));
    assert.deepEqual(detalleTarjetasDiario([{folio: "MIXTO", total: 100, pagos: [{metodoPago: "efectivo", monto: 40}, {metodoPago: "tarjeta", monto: 60, terminalAlias: "Caja 1", tarjetaTipo: "debito"}]}]), [{folio: "MIXTO", terminal: "Caja 1", tipo: "debito", monto: 60}]);
    const futuro = new Date(now.getTime() + 3 * 86400000);
    await Caja.create({sucursalId: a._id, usuarioAperturaId: gerente._id, efectivoInicial: 1000, fechaApertura: futuro});
    const antes = await (await corteDiario(req(`/api/cortes/diario?dia=2000-01-01`))).text();
    assert.ok(!antes.includes("Turnos pendientes de cerrar"), "No incluye cajas abiertas después del día consultado");
    await Caja.updateMany({}, {estado: "cerrada", fechaCierre: now});
    const cerradas = await (await corteDiario(req(`/api/cortes/diario?dia=${day}`))).text();
    assert.ok(!cerradas.includes("Turnos pendientes de cerrar"), "No anuncia pendientes si ya cerraron dentro del día");
    await Caja.findByIdAndUpdate(caja._id, {estado: "abierta", fechaCierre: null, fechaApertura: new Date(now.getTime()-86400000)});
    assert.equal((await configurar(req("/api/configuracion","PATCH",{reglasOperacion:reglasCosto}))).status,200);
    await Producto.findByIdAndUpdate(p1._id,{fiscal:fiscalCosto});
    const proveedor = await Proveedor.create({nombre:"Proveedor prueba"});
    const compra = await OrdenCompra.create({folio:"OC-TEST",proveedorId:proveedor._id,estado:"solicitada",items:[{productoId:p1._id,nombreProducto:p1.nombre,cantidadOrdenada:2,precioUnitario:100}]});
    const compraBody = {items:[{productoId:String(p1._id),cantidadRecibida:2,costoUnitario:100,notaRecepcion:""}],financiero:{moneda:"USD",tipoCambio:18,servicio:10,descuento:5,observaciones:"Prueba"}};
    const paramsCompra = {params:Promise.resolve({id:String(compra._id)})};
    const stockAntes = (await Producto.findById(p1._id)).existenciaMatriz;
    assert.equal((await recibirCompra(req("/api/ordenes-compra/recibir","POST",{...compraBody,financiero:{...compraBody.financiero,descuento:9999}}),paramsCompra)).status,400);
    assert.equal((await Producto.findById(p1._id)).existenciaMatriz,stockAntes,"Rollback si el total es inválido");
    const recibida = await recibirCompra(req("/api/ordenes-compra/recibir","POST",compraBody),paramsCompra);
    assert.equal(recibida.status,200,await recibida.clone().text());
    const recibidaData = await recibida.json();
    assert.equal(recibidaData.recepcionCostos.total,242.6);
    assert.equal(recibidaData.recepcionCostos.folio,"000001");
    assert.equal((await recibirCompra(req("/api/ordenes-compra/recibir","POST",compraBody),paramsCompra)).status,409);
    assert.equal((await Producto.findById(p1._id)).existenciaMatriz,stockAntes+2);
    assert.equal((await configurar(req("/api/configuracion","PATCH",{reglasOperacion:{...reglasCosto,turnoAnterior:"bloquear"}},gerenteToken))).status,401);
    await configurar(req("/api/configuracion","PATCH",{reglasOperacion:{...reglasCosto,turnoAnterior:"bloquear"}}));
    assert.equal((await vender(req("/api/ventas","POST",{...ventaBody,clienteOperacionId:"turno-antiguo"},gerenteToken))).status,409);
    assert.equal(await Venta.countDocuments({clienteOperacionId:"turno-antiguo"}),0);
    await configurar(req("/api/configuracion","PATCH",{reglasOperacion:reglasCosto}));
    const correccionBody = {folio:venta.folio,dia:"2026-09-01",motivo:"Corrección administrativa de prueba"};
    assert.equal((await corregirDia(req("/api/ventas/corregir-dia","POST",correccionBody))).status,400);
    await configurar(req("/api/configuracion","PATCH",{reglasOperacion:{...reglasCosto,permitirCorreccionDia:true}}));
    assert.equal((await corregirDia(req("/api/ventas/corregir-dia","POST",correccionBody,gerenteToken))).status,401);
    const previa = await Venta.findById(venta._id).lean();
    assert.equal((await corregirDia(req("/api/ventas/corregir-dia","POST",correccionBody))).status,200);
    const corregida = await Venta.findById(venta._id).lean();
    assert.equal(corregida.fecha.toISOString(),previa.fecha.toISOString());
    assert.equal(String(corregida.cajaSesionId),String(previa.cajaSesionId));
    assert.deepEqual(corregida.pagos,previa.pagos);
    assert.equal(corregida.correccionesDia.length,1);
    assert.equal((await corregirDia(req("/api/ventas/corregir-dia","POST",correccionBody))).status,400);
    console.log("OK: fondo central, permisos, importe manipulado y desactualizado, apertura idempotente y aislada, corte con/sin notas y validación de fecha.");
    console.log("OK: catálogo consolidado idempotente, gerente solo lectura global y NIP local, arqueos sin duplicación/signos, promociones combinadas/kilos/prioridad y cobro real con idempotencia.");
    if (process.argv.includes("--serve")) {
      server = spawn("npm", ["run", "dev", "--", "--port", "3100"], { stdio: "inherit", env: { ...process.env } });
      await new Promise<void>((resolve) => { server!.on("exit", () => resolve()); process.on("SIGTERM", () => { server?.kill(); resolve(); }); });
    }
  } finally { server?.kill(); await mongoose.disconnect(); await mongo.stop(); }
}
main().catch((e) => { console.error(e); process.exitCode = 1; });
